### ISSUE TITLE
implementing the Gertensgarbe-Werner estimator in R

### ISSUE THREAD

**Issue by spedygiorgio** [TReynkens/ReIns#1]
Hi, I am impatient to see this book published... Btw, I was wondering wether there are any plan to implement a function for the Gertensgarbe-Werner estimator. Once I was given a matlab code that I attach 
[GartensGarbe.m.txt](https://github.com/TReynkens/ReIns/files/701862/GartensGarbe.m.txt) that migth be helpful

**Comment by TReynkens** [comment]
Hi,
Thank you for the interest in the book (and package). The book will be published later this year (probably second part of the year).

As the Gertensgarbe-Werner estimator is not used in the book, it is not implemented in the package. Moreover, there are no plans for the moment to include it. However, if we would decide to include it in the future, the Matlab code can be handy. So, thank you for providing it!
